name: "functions_getworkdirs"
description: A function for extracting work directories from Nextflow channels.
keywords:
  - function
  - work
  - clean
input:
  - ch_to_clean:
      type: channel
      description: A Nextflow channel containing files to be cleaned.
  - ch_downstream:
      type: channel
      description: A Nextflow channel containing files produced downstream of files that will be cleaned.
output:
  - ch_workdirs:
      type: channel
      description: A nextflow channel containing the meta.id and the work directory path to be cleaned.
authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
