name: "functions_rmemptyfastqs"
description: A function for removing empty FastQ files from Nextflow channels.
keywords:
  - function
  - work
  - empty
  - fastq
input:
  - ch_fastqs:
      type: channel
      description: A Nextflow channel containing FastQ files.
output:
  - ch_nonempty_fastqs:
      type: channel
      description: A Nextflow channel containing only channel objects with non-empty FastQ files.
authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
